### ISSUE TITLE
R2 fails on empty files

### ISSUE THREAD

**Issue by hosamaly** [ded/R2#5]
Calling `r2` on an empty file causes the following error:

``` javascript
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Cannot call method 'map' of null
    at r2 (/home/ubuntu1204/code/github/R2/r2.js:101:49)
    at Object.exec (/home/ubuntu1204/code/github/R2/r2.js:134:25)
    at Object.<anonymous> (/home/ubuntu1204/code/github/R2/bin/r2:2:21)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:41)
```

**Comment by hosamaly** [comment]
The user would face the same error if the input file does not contain any valid CSS markup (e.g. an SCSS file containing only `@import` statements).

**Comment by ded** [comment]
how did your fixes end up going?

**Comment by hosamaly** [comment]
They seem to be working fine. I only used them once, but they performed nicely.

However, I would suggest splitting the code that performs the conversion from the code that attempts to minify the file if possible, preferably adding a switch for minification.
